# build environment
FROM node:14.18.1-buster as build
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY . ./
RUN npm install

# Add docker-compose-wait tool
ENV WAIT_VERSION 2.9.0
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait ./
RUN chmod +x /app/wait

ENV PORT=$PORT \  
  DB_HOST= \
  DB_PORT= \
  DB_USER= \
  DB_PASSWORD= \
  DB_NAME= 
