# build environment
FROM node:14.18.1-buster as build
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY . ./
RUN npm install

ENV PORT=$PORT \  
  DB_HOST= \
  DB_PORT= \
  DB_USER= \
  DB_PASSWORD= \
  DB_NAME= 
